org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configureondemand=true

mod_id=better_death_screen
mod_name=Better Death Screen
mod_version=1.0.0
maven_group=com.phiro
author=TheMFCraft

# Default Architectury (overridden per subproject where needed)
architectury_version=13.0.8
architectury_plugin_version=3.4.162
