def modId = rootProject.findProperty('mod_id') ?: 'better_death_screen'

architectury {
    platformSetupLoomIde()
    neoForge()
}

repositories {
    maven { url = 'https://maven.neoforged.net/releases/' }
}

configurations {
    common
    shadowCommon
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentNeoForge.extendsFrom common
}

dependencies {
    neoForge "net.neoforged:neoforge:${project.neoforge_version}"
    modImplementation "dev.architectury:architectury-neoforge:${project.architectury_version}"
    common(project(path: ':common', configuration: 'namedElements')) { transitive false }
    shadowCommon(project(path: ':common', configuration: 'transformProductionNeoForge')) { transitive false }
}

loom {
    mods {
        "${modId}" {
            sourceSet sourceSets.main
        }
    }
}
